name: GitHub_Actions_Practice

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  
jobs:
    build_and_test:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest

      - name: Run tests
        run: |
          pytest

    build_and_deploy:
      needs: build_and_test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to DockerHun
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
          
        - name: Image digest
          run: echo ${{ steps.build_and_deploy.outputs.digest }}
